#!/bin/bash

# There's few reliable RPM source for git, thus the script builds the binary from source.

target="git-2.0.5"
tarname="$target.tar.gz"
basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

sudo su - root -c "yum -y groupinstall \"Development Tools\""
sudo su - root -c "yum -y install expat-devel curl-devel zlib-devel perl-ExtUtils-MakeMaker asciidoc xmlto openssl-devel"

if [ ! -f "$basedir/$tarname" ]; then
	sudo su - root -c "wget --directory-prefix=$basedir https://www.kernel.org/pub/software/scm/git/$tarname"
fi

if [ ! -d "$basedir/$target" ]; then
	sudo su - root -c "tar xzf $basedir/$tarname -C $basedir"
fi


# remove old version of git
sudo su - root -c "yum -y remove git"

sudo su - root -c "cd $basedir/$target; make prefix=/usr all"
sudo su - root -c "cd $basedir/$target; make prefix=/usr install"

if [ -f "$basedir/$tarname" ]; then
	sudo su - root -c "rm -rf $basedir/$tarname"
fi

if [ -d "$basedir/$target" ]; then
	sudo su - root -c "rm -rf $basedir/$target"
fi

