#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# load CentOS-Base.repo
sudo su - root -c "cat $basedir/base_repo_template.conf > /etc/yum.repos.d/CentOS-Base.repo"

# install development tools
sudo su - root -c "yum -y groupinstall development"

# install epel repo
sudo su - root -c "yum -y install epel-release"

# install other tools
sudo su - root -c "yum -y install unzip libtool autoconf automake"

# install system logging utility `sar`
sudo su - root -c "yum -y install sysstat"
