#!/bin/bash

if [ $# -ne 2 ]; then 
	echo "Usage: $0 <ip> <number of mask bits>"
	exit 1
fi

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

ip=$1
nmaskbits=$2
inIface=eth0
outIface=eth0

sudo su - root -c "iptables -t nat -A POSTROUTING -s $ip/$nmaskbits --in-interface $inIface --out-interface $outIface -j MASQUERADE"

sudo su - root -c "$basedir/backup"
